package Package_addressbook.tests;// Generated by Selenium IDE
import Package_addressbook.model.GroupData;
import org.junit.Test;

public class Test1 extends TestBase {

    @Test
    public void testGroupCreation() {
        app.gotoGroupPage();
        app.getGroupHelper().initGroupCreation();
        app.getGroupHelper().fillGroupForm(new GroupData("tt1", "tt2", "tt3"));
        app.getGroupHelper().submitGroupCreation();
        app.getGroupHelper().returnToGroupPage();
    }

}