package Package_addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;

public class Test2 extends TestBase {

    @Test
    public void testGroupDelete() {
        app.gotoGroupPage();
        app.getGroupHelper().selectGroup();
        app.getGroupHelper().deleteSelectedGroups();
        app.getGroupHelper().returnToGroupPage();
    }

}
