package Package_addressbook;// Generated by Selenium IDE
import org.junit.Test;

public class Test1 extends TestBase {

    @Test
    public void testGroupCreation() {
        gotoGroupPage();
        initGroupCreation();
        fillGoupForm(new GroupData("tt1", "tt2", "tt3"));
        submitGroupCreation();
        returnToGroupPage();
    }

}