package Package_addressbook;// Generated by Selenium IDE
import org.junit.Test;

public class Test2 extends TestBase {

    @Test
    public void test2() {
        gotoGroupPage();
        selectGroup();
        deleteSelectedGroups();
        returnToGroupPage();
    }

}
